# Generated by Django 3.1.6 on 2021-02-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_newsletter',
            name='emailAddress',
            field=models.EmailField(max_length=256, unique=True),
        ),
    ]
