# Generated by Django 3.1.6 on 2021-02-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210218_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='Description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='slider',
            name='Name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
