# Generated by Django 3.1.6 on 2021-02-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210216_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryImage',
            field=models.ImageField(upload_to='category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='productImage',
            field=models.ImageField(upload_to='products'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subCategoryImage',
            field=models.ImageField(upload_to='subcategory'),
        ),
    ]
