# Generated by Django 3.1.6 on 2021-02-16 03:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210216_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_newsletter',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
