# Generated by Django 3.1.6 on 2021-02-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_email_newsletter_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryImage',
            field=models.ImageField(upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='productImage',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subCategoryImage',
            field=models.ImageField(upload_to='subcategory/'),
        ),
    ]
