# Generated by Django 3.0.5 on 2021-02-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210224_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='productDescription',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
