# Generated by Django 3.1.6 on 2021-02-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_productdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryDescription',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
