# Generated by Django 3.1.6 on 2021-03-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_categorydescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productDescription',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
