# Generated by Django 3.1.6 on 2021-03-24 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210301_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contactEmail', models.EmailField(max_length=255)),
                ('message', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='Name',
            new_name='Heading',
        ),
        migrations.AddField(
            model_name='category',
            name='productImg',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awardImage', models.ImageField(upload_to='awards/')),
                ('awardCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', to_field='categoryName')),
            ],
            options={
                'verbose_name': 'Award',
                'verbose_name_plural': 'Awards',
            },
        ),
    ]
